name: dp-sgd-py312-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy~=1.26.4
  - pandas~=2.2.2
  - matplotlib~=3.9.2
  - pillow~=10.4.0
  - tqdm~=4.66.5
  - pytest>=7.4.0
  - pip:
      - torch>=2.2
      - torchvision>=0.17
      - opacus>=1.4
      - kagglehub>=0.2.5
